import patients from '../../data/patients';
import { Patient, PatientWithoutSSN, NewPatient } from '../types';
import { v1 as uuid } from 'uuid';

const getPatients = ():Patient[] => {
    return patients;
};

const getPatientsWithoutSSN = ():PatientWithoutSSN[] => {
    return patients.map(({id,name,dateOfBirth,gender,occupation})=>({
        id,
        name,
        dateOfBirth,
        gender,
        occupation
    }));
};

const addPatient = (
    patient: NewPatient//patient consists of every field except id (newpatient type)
  ): Patient => {//return patient object
    const id = uuid();//id generated by uuid
    const newPatient = {
      id: id,
      ...patient  
    };
  
    patients.push(newPatient);
    return newPatient;
  };

export default{
    getPatients,
    getPatientsWithoutSSN,
    addPatient
};